config/routes.rb
Rails.application.routes.draw do
  get 'users/find_user' => 'users#find_user', as: :find_user
  post 'users/follow' => 'users#follow', as: :follow
  delete 'users/unfollow' => 'users#unfollow', as: :unfollow
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show]
  root :to => "timelines#index"
  resources :plurks
  get 'plurks/:id/reply' => 'plurks#reply', as: :reply_plurk
  post 'plurks/:id/reply' => 'plurks#create_reply', as: :create_reply_plurk

  scope '/api/v1', defaults: {format: 'json'} do
    get 'users/followings' => 'users#followings'
    get 'users/followers'  => 'users#followers'
    resources :plurks
    resources :timelines, only: [:index]
    get 'plurks/:id/reply' => 'plurks#reply'
    post 'plurks/:id/reply' => 'plurks#create_reply'
    post 'sign_in' => 'verifications#create'
    delete 'sign_out' => 'verifications#destroy'
  end

end

app/models/plurk.rb
class Plurk < ActiveRecord::Base
  has_many :replies, :dependent => :destroy
  belongs_to :user
  validates_presence_of :user_id
  validates_presence_of :content
end

app/controllers/plurks_controller.rb
class PlurksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plurk, only: [:destroy, :update, :edit, :reply, :create_reply]
  respond_to :html, :josn
  def index
    @plurks = current_user.plurks.order(created_at: :desc)
  end
  def new
    @plurk = Plurk.new
  end
  def create
    @plurk = current_user.plurks.new(plurk_params)
    if @plurk.valid?
      @plurk.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: @plurk, :success => true }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: {message: 'Error: Invaild params'} }
      end
    end
  end
  def show
    @plurks = Plurk.where(user_id: [current_user.id, current_user.following_ids], id: params[:id]).order(created_at: :desc)
    if !@plurks.present?
      respond_to do |format|
        format.html { redirect_to plurks_path, alert: "No such Plurk"}
        format.json { render json: {message: 'No such Plurk'} }
      end
    end
  end
  def destroy
    if @plurk.user == current_user
      @plurk.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json {render json: {message: 'Deleted plurk'}}
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, alert: "permission denied!" }
        format.json { render json: {message: 'permission denied!'} }
      end
    end
  end
  def update
    if @plurk.user == current_user
      @plurk.update(plurk_params)
      redirect_to root_path
    else
      redirect_to root_path, alert: "permission denied!"
    end
  end
  def reply
    @reply = Reply.new
  end
  def create_reply
    @reply = @plurk.replies.new(reply_params)
    if @reply.save
      redirect_to root_path
    else
      render :reply
    end
  end

  private
  def plurk_params
    params.require(:plurk).permit(:content)
  end
  def reply_params
    params.require(:reply).permit(:plurk_id,:content).merge(user: current_user)
  end
  def set_plurk
    @plurk = Plurk.find(params[:id])
  end

end

app/helpers/plurks_helper.rb
module PlurksHelper
end

app/views/plurks/_allpost.html.erb
<% @plurks.each do |plurk| %>
  <div class="plurk-main">
    <%= render partial: 'plurks/button_delete', locals: {plurk: plurk} %>
    <div class="row plurk-body">
        <div class="col col-md-2 col-xs-2">
          <%= image_tag plurk.user.avatar.url(:thumb), size: "60x60", alt: "avatar" %>
        </div>
        <div class="col-md-10 col-xs-10">
          <%= link_to plurk.user.nickname, user_path(plurk.user) %> <span class="plurk-time"> <%= l plurk.created_at, format: :short %> </span>
          <%= render partial: 'plurks/button_edit', locals: {plurk: plurk} %>
          <%= render partial: 'plurks/button_reply', locals: {plurk: plurk} %>
          <div class="plurk-content">
            <%= plurk.content %>
          </div>
          <div class="collapse" id="collapse-reply-id-<%= plurk.id %>">
            <%= render partial: 'plurks/reply_input', locals: {plurk: plurk} %>
          </div>
        </div>
    </div>
    <% if plurk.replies.present? %>
      <% plurk.replies.each do |reply| %>
        <div class="row plurk-reply">
          <div class="col-md-2 col-xs-2">
            <%= image_tag plurk.user.avatar.url(:thumb), size: "60x60", alt: "avatar" %>
          </div>
          <div class="col-md-10 col-xs-10">
            <%= link_to reply.user.nickname, user_path(reply.user) %>
            <span class="plurk-time"><%= l reply.created_at, format: :short %> </span>
            <div class="reply-content">
              <%= reply.content %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/plurks/_button_delete.html.erb
<% if plurk.user == current_user %>
  <button type="button" class="close" data-toggle="modal" data-target="#delete-plurk-id-<%= plurk.id %>">
    <span aria-hidden="true">&times;</span>
  </button>
<% end %>
<!-- Modal -->
<div class="modal fade" id="delete-plurk-id-<%= plurk.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">ARE YOU SURE?</h4>
      </div>
      <div class="modal-footer">
        <%= link_to 'Delete', plurk, method: :delete, class: "btn btn-danger", type: "button" %>
        <button type="button" class="btn btn-success" data-dismiss="modal">No, I don't want to delete it</button>
      </div>
    </div>
  </div>
</div>

app/views/plurks/_button_edit.html.erb
<button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#plurk-content-id-<%= plurk.id %>">
  Edit
</button>
<!-- Modal -->
<div class="modal fade" id="plurk-content-id-<%= plurk.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Plurk</h4>
      </div>
      <%= form_for plurk do |f| %>
        <div class="modal-body">
          <%= f.text_area :content, :required=>true %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Save changes", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/plurks/_button_reply.html.erb
      <button class="btn btn-default btn-xs"  type="button" data-toggle="collapse" data-target="#collapse-reply-id-<%= plurk.id %>" aria-expanded="false" aria-controls="collapse-reply-id-<%= plurk.id %>">
        ↪︎ Reply
      </button>

app/views/plurks/_form.html.erb
<%= form_for(@plurk) do |f| %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plurks/_new.html.erb
<% @plurk=Plurk.new %>
<%= form_for(@plurk) do |f| %>
  <div class="row">
    <div class="col-md-9 col-xs-9">
      <%= f.text_area :content, class: "form-control", rows: "1", placeholder: "Have something to poo?", required: true %>
    </div>
    <div class="col-md-1 col-xs-1">
      <%= f.submit "Plurk", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/plurks/_reply_input.html.erb
<% @reply = Reply.new %>
<%= form_for @reply, :url => reply_plurk_path(plurk) do |f| %>
  <div class="field">
    <%= f.text_area :content, class: "form-control", rows: "1", placeholder: "What do you want to say?" %>
    <%= f.submit "Reply", class: "btn btn-default" %>
  </div>
<% end %>

app/views/plurks/edit.html.erb
<h1>Edit Plurk</h1>
<%= render 'form' %>
<%= link_to 'Home', plurks_path %>

app/views/plurks/index.html.erb
<%= render 'plurks/new' %>
<%= render 'plurks/allpost' %>

app/views/plurks/new.html.erb
<h1>New Plurk</h1>
<%= render 'form' %>
<%= link_to 'Home', plurks_path %>

app/views/plurks/reply.html.erb
<h1>Reply Plurk</h1>
<%= form_for @reply, :url => reply_plurk_path(@plurk) do |f| %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Home', plurks_path %>

app/views/plurks/show.html.erb
<%= render 'plurks/new' %>
<%= render 'plurks/allpost' %>