config/routes.rb
Rails.application.routes.draw do
  get 'users/find_user' => 'users#find_user', as: :find_user
  post 'users/follow' => 'users#follow', as: :follow
  delete 'users/unfollow' => 'users#unfollow', as: :unfollow
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show]
  root :to => "timelines#index"
  resources :plurks
  get 'plurks/:id/reply' => 'plurks#reply', as: :reply_plurk
  post 'plurks/:id/reply' => 'plurks#create_reply', as: :create_reply_plurk

  scope '/api/v1', defaults: {format: 'json'} do
    get 'users/followings' => 'users#followings'
    get 'users/followers'  => 'users#followers'
    resources :plurks
    resources :timelines, only: [:index]
    get 'plurks/:id/reply' => 'plurks#reply'
    post 'plurks/:id/reply' => 'plurks#create_reply'
    post 'sign_in' => 'verifications#create'
    delete 'sign_out' => 'verifications#destroy'
  end

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Fake Plurk', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to('Find User', find_user_path)%></li>
          <li><%= link_to('User Info', user_path(current_user)) %></li>
          <li><%= link_to('Change password', edit_registration_path(:user)) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><%= link_to('Register', new_registration_path(:user)) %></li>
          <li><%= link_to('Login', new_session_path(:user)) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo03</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
    <%= yield %>
  </div>

<footer>
  <div class="container">
    Fake Plurk
  </div>
</footer>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>